const images = [
  {
    author: 'Павел Федотов',
    picture: 'Сватовство майора',
    year: '1852',
    imageNum: '0',
  },
  {
    author: 'Эдгар Дега',
    picture: 'Голубые танцовщицы',
    year: '1897',
    imageNum: '1',
  },
  {
    author: 'Веронезе',
    picture: 'Пир в доме Левия',
    year: '1563',
    imageNum: '2',
  },
  {
    author: 'Илья Репин',
    picture: 'Иван Грозный и сын его Иван',
    year: '1885',
    imageNum: '3',
  },
  {
    author: 'Константин Маковский',
    picture: 'Портрет графини Софьи',
    year: '1890',
    imageNum: '4',
  },
  {
    author: 'Василий Перов',
    picture: 'Приезд гувернантки в купеческий дом',
    year: '1866',
    imageNum: '5',
  },
  {
    author: 'Микеланджело',
    picture: 'Сотворение Адама',
    year: '1511',
    imageNum: '6',
  },
  {
    author: 'Пьер Огюст Ренуар',
    picture: 'Прогулка в Булонском лесу',
    year: '1873',
    imageNum: '7',
  },
  {
    author: 'Ян Вермеер',
    picture: 'Хозяйка и служанка',
    year: '1667',
    imageNum: '8',
  },
  {
    author: 'Василий Поленов',
    picture: 'Московский дворик',
    year: '1877',
    imageNum: '9',
  },
  {
    author: 'Фёдор Васильев',
    picture: 'Мокрый луг',
    year: '1872',
    imageNum: '10',
  },
  {
    author: 'Илья Репин',
    picture: 'Проводы новобранца',
    year: '1879',
    imageNum: '11',
  },
  {
    author: 'Веронезе',
    picture: 'Марс и Венера',
    year: '1560',
    imageNum: '12',
  },
  {
    author: 'Виктор Васнецов',
    picture: 'Аленушка',
    year: '1881',
    imageNum: '13',
  },
  {
    author: 'Клод Лоррен',
    picture: 'Отплытие святой Урсулы',
    year: '1614',
    imageNum: '14',
  },
  {
    author: 'Илья Репин',
    picture: 'Вечорници',
    year: '1881',
    imageNum: '15',
  },
  {
    author: 'Жан Фрагонар',
    picture: 'Качели',
    year: '1767',
    imageNum: '16',
  },
  {
    author: 'Архип Куинджи',
    picture: 'Берёзовая роща',
    year: '1879',
    imageNum: '17',
  },
  {
    author: 'Пабло Пикассо',
    picture: 'Герника',
    year: '1937',
    imageNum: '18',
  },
  {
    author: 'Поль Гоген',
    picture: 'Откуда мы пришли? Кто мы? Куда мы идём?',
    year: '1898',
    imageNum: '19',
  },
  {
    author: 'Бартоломео Мурильо',
    picture: 'Мадонна с четками',
    year: '1655',
    imageNum: '20',
  },
  {
    author: 'Питер Брейгель',
    picture: 'Фламандские пословицы',
    year: '1559',
    imageNum: '21',
  },
  {
    author: 'Ян ван Эйк',
    picture: 'Портрет четы Арнольфини',
    year: '1434',
    imageNum: '22',
  },
  {
    author: 'Питер Брейгель',
    picture: 'Избиение младенцев',
    year: '1567',
    imageNum: '23',
  },
  {
    author: 'Константин Маковский',
    picture: 'Дети, бегущие от грозы',
    year: '1872',
    imageNum: '24',
  },
  {
    author: 'Рембрандт',
    picture: 'Даная',
    year: '1647',
    imageNum: '25',
  },
  {
    author: 'Рафаэль',
    picture: 'Мадонна в кресле',
    year: '1514',
    imageNum: '26',
  },
  {
    author: 'Василий Суриков',
    picture: 'Взятие снежного городка',
    year: '1891',
    imageNum: '27',
  },
  {
    author: 'Иван Шишкин',
    picture: 'Ручей в берёзовом лесу',
    year: '1883',
    imageNum: '28',
  },
  {
    author: 'Василий Суриков',
    picture: 'Покорение Сибири Ермаком Тимофеевичем',
    year: '1895',
    imageNum: '29',
  },
  {
    author: 'Владимир Боровиковский',
    picture: 'Портрет Лопухиной',
    year: '1797',
    imageNum: '30',
  },
  {
    author: 'Рене Магритт',
    picture: 'Сын человеческий',
    year: '1964',
    imageNum: '31',
  },
  {
    author: 'Веласкес',
    picture: 'Венера с зеркалом',
    year: '1651',
    imageNum: '32',
  },
  {
    author: 'Иван Богданов',
    picture: 'За расчётом',
    year: '1890',
    imageNum: '33',
  },
  {
    author: 'Рембрандт',
    picture: 'Христос и грешница',
    year: '1644',
    imageNum: '34',
  },
  {
    author: 'Джон Уильям Уотерхаус',
    picture: 'Волшебница Шалот',
    year: '1888',
    imageNum: '35',
  },
  {
    author: 'Пьер Огюст Ренуар',
    picture: 'Большие купальщицы',
    year: '1887',
    imageNum: '36',
  },
  {
    author: 'Бартоломео Мурильо',
    picture: 'Мальчик с собакой',
    year: '1650',
    imageNum: '37',
  },
  {
    author: 'Василий Перов',
    picture: 'Тройка',
    year: '1866',
    imageNum: '38',
  },
  {
    author: 'Николай Богданов-Бельский',
    picture: 'Устный счёт',
    year: '1895',
    imageNum: '39',
  },
  {
    author: 'Виктор Васнецов',
    picture: 'Три царевны подземного царства',
    year: '1884',
    imageNum: '40',
  },
  {
    author: 'Анри Матисс',
    picture: 'Танец',
    year: '1910',
    imageNum: '41',
  },
  {
    author: 'Эдвард Мунк',
    picture: 'Мадонна',
    year: '1894',
    imageNum: '42',
  },
  {
    author: 'Марк Шагал',
    picture: 'Прогулка',
    year: '1918',
    imageNum: '43',
  },
  {
    author: 'Василий Перов',
    picture: 'Сельский крестный ход на Пасхе',
    year: '1861',
    imageNum: '44',
  },
  {
    author: 'Иероним Босх',
    picture: 'Страшный суд',
    year: '1504',
    imageNum: '45',
  },
  {
    author: 'Карл Лемох',
    picture: 'Варька',
    year: '1893',
    imageNum: '46',
  },
  {
    author: 'Жан Фрагонар',
    picture: 'Поцелуй украдкой',
    year: '1788',
    imageNum: '47',
  },
  {
    author: 'Франсуа Буше',
    picture: 'Венера, утешающая Амура',
    year: '1751',
    imageNum: '48',
  },
  {
    author: 'Иван Шишкин',
    picture: 'Корабельная роща',
    year: '1898',
    imageNum: '49',
  },
  {
    author: 'Густав Климт',
    picture: 'Золотая Адель',
    year: '1907',
    imageNum: '50',
  },
  {
    author: 'Виктор Васнецов',
    picture: 'Богатыри',
    year: '1898',
    imageNum: '51',
  },
  {
    author: 'Вильгельм фон Каульбах',
    picture: 'Разрушение Иерусалима',
    year: '1846',
    imageNum: '52',
  },
  {
    author: 'Веронезе',
    picture: 'Брак в Кане Галилейской',
    year: '1562',
    imageNum: '53',
  },
  {
    author: 'Андрей Рублев',
    picture: 'Троица',
    year: '1411',
    imageNum: '54',
  },
  {
    author: 'Василий Суриков',
    picture: 'Утро стрелецкой казни',
    year: '1881',
    imageNum: '55',
  },
  {
    author: 'Тициан',
    picture: 'Вакханалия',
    year: '1526',
    imageNum: '56',
  },
  {
    author: 'Веласкес',
    picture: 'Вилла Медичи в Риме. Полдень',
    year: '1630',
    imageNum: '57',
  },
  {
    author: 'Эдуард Мане',
    picture: 'Ланч на траве',
    year: '1863',
    imageNum: '58',
  },
  {
    author: 'Сальвадор Дали',
    picture: 'Постоянство памяти',
    year: '1931',
    imageNum: '59',
  },
  {
    author: 'Пьер Огюст Ренуар',
    picture: 'Две девушки',
    year: '1892',
    imageNum: '60',
  },
  {
    author: 'Александр Маковский',
    picture: 'Надоела',
    year: '1897',
    imageNum: '61',
  },
  {
    author: 'Веласкес',
    picture: 'Менины',
    year: '1656',
    imageNum: '62',
  },
  {
    author: 'Антонис ван Дейк',
    picture: 'Самсон и Далила',
    year: '1628',
    imageNum: '63',
  },
  {
    author: 'Пабло Пикассо',
    picture: 'Девочка на шаре',
    year: '1905',
    imageNum: '64',
  },
  {
    author: 'Джованни Беллини',
    picture: 'Пир богов',
    year: '1514',
    imageNum: '65',
  },
  {
    author: 'Леонардо да Винчи',
    picture: 'Дама с горностаем',
    year: '1490',
    imageNum: '66',
  },
  {
    author: 'Веласкес',
    picture: 'Бахус',
    year: '1628',
    imageNum: '67',
  },
  {
    author: 'Бартоломео Мурильо',
    picture: 'Непорочное зачатие',
    year: '1678',
    imageNum: '68',
  },
  {
    author: 'Теодор Жерико',
    picture: 'Плот "Медузы"',
    year: '1819',
    imageNum: '69',
  },
  {
    author: 'Иван Шишкин',
    picture: 'Утро в сосновом лесу',
    year: '1889',
    imageNum: '70',
  },
  {
    author: 'Жан Этьен Лиотар',
    picture: 'Шоколадница',
    year: '1745',
    imageNum: '71',
  },
  {
    author: 'Рембрандт',
    picture: 'Автопортрет с Саскией',
    year: '1635',
    imageNum: '72',
  },
  {
    author: 'Илья Репин',
    picture: 'Крестный ход',
    year: '1883',
    imageNum: '73',
  },
  {
    author: 'Алексей Венецианов',
    picture: 'Спящий пастушок',
    year: '1826',
    imageNum: '74',
  },
  {
    author: 'Иван Богданов',
    picture: 'Новичок',
    year: '1893',
    imageNum: '75',
  },
  {
    author: 'Анри де Тулуз-Лотрек',
    picture: 'Угол Мулен де ла Галет',
    year: '1892',
    imageNum: '76',
  },
  {
    author: 'Тициан',
    picture: 'Кающаяся Марина Магдалина',
    year: '1565',
    imageNum: '77',
  },
  {
    author: 'Веласкес',
    picture: 'Инфанта Маргарита',
    year: '1654',
    imageNum: '78',
  },
  {
    author: 'Тициан',
    picture: 'Динарий Кесаря',
    year: '1516',
    imageNum: '79',
  },
  {
    author: 'Карл Брюллов',
    picture: 'Всадница',
    year: '1832',
    imageNum: '80',
  },
  {
    author: 'Василий Верещагин',
    picture: 'Апофеоз войны',
    year: '1817',
    imageNum: '81',
  },
  {
    author: 'Леонардо да Винчи',
    picture: 'Благовещение',
    year: '1475',
    imageNum: '82',
  },
  {
    author: 'Алексей Саврасов',
    picture: 'Грачи прилетели',
    year: '1871',
    imageNum: '83',
  },
  {
    author: 'Тициан',
    picture: 'Любовь земная и Любовь небесная',
    year: '1516',
    imageNum: '84',
  },
  {
    author: 'Жан Батист Грёз',
    picture: 'Деревенская помолвка',
    year: '1761',
    imageNum: '85',
  },
  {
    author: 'Пабло Пикассо',
    picture: 'Авиньонские девицы',
    year: '1907',
    imageNum: '86',
  },
  {
    author: 'Илья Репин',
    picture: 'Бурлаки на Волге',
    year: '1873',
    imageNum: '87',
  },
  {
    author: 'Михаил Нестеров',
    picture: 'Видение отроку Варфоломею',
    year: '1890',
    imageNum: '88',
  },
  {
    author: 'Рафаэль',
    picture: 'Мадонна Бельведерская',
    year: '1506',
    imageNum: '89',
  },
  {
    author: 'Василий тропинин',
    picture: 'Девушка с горшком роз',
    year: '1850',
    imageNum: '90',
  },
  {
    author: 'Караваджо',
    picture: 'Лютнист',
    year: '1596',
    imageNum: '91',
  },
  {
    author: 'Василий Перов',
    picture: 'Охотники на привале',
    year: '1871',
    imageNum: '92',
  },
  {
    author: 'Леонардо да Винчи',
    picture: 'Тайная вечеря',
    year: '1498',
    imageNum: '93',
  },
  {
    author: 'Жан Батист Грёз',
    picture: 'Избалованное дитя',
    year: '1765',
    imageNum: '94',
  },
  {
    author: 'Адольф Вильям Бугро',
    picture: 'Волна',
    year: '1896',
    imageNum: '95',
  },
  {
    author: 'Кузьма Петров-Водкин',
    picture: 'Купание красного коня',
    year: '1912',
    imageNum: '96',
  },
  {
    author: 'Густав Климт',
    picture: 'Поцелуй',
    year: '1908',
    imageNum: '97',
  },
  {
    author: 'Иван Шишкин',
    picture: 'Рожь',
    year: '1878',
    imageNum: '98',
  },
  {
    author: 'Жан-Леон Жером',
    picture: 'Бой гладиаторов',
    year: '1872',
    imageNum: '99',
  },
  {
    author: 'Василий Суриков',
    picture: 'Боярыня Морозова',
    year: '1887',
    imageNum: '100',
  },
  {
    author: 'Исаак Левитан',
    picture: 'Над вечным покоем',
    year: '1894',
    imageNum: '101',
  },
  {
    author: 'Гейнсборо',
    picture: 'Дама в голубом',
    year: '1780',
    imageNum: '102',
  },
  {
    author: 'Алексей Венецианов',
    picture: 'На пашне. Весна',
    year: '1820',
    imageNum: '103',
  },
  {
    author: 'Тициан',
    picture: 'Саломея',
    year: '1515',
    imageNum: '104',
  },
  {
    author: 'Василий Кандинский',
    picture: 'Композиция VIII',
    year: '1923',
    imageNum: '105',
  },
  {
    author: 'Василий Поленов',
    picture: 'В парке',
    year: '1874',
    imageNum: '106',
  },
  {
    author: 'Луи Лагрене',
    picture: 'Марс и Венера',
    year: '1770',
    imageNum: '107',
  },
  {
    author: 'Сальвадор Дали',
    picture: 'Сон, вызванный полётом пчелы вокруг граната, за секунду до пробуждения',
    year: '1944',
    imageNum: '108',
  },
  {
    author: 'Ян Вермеер',
    picture: 'Девушка с жемчужной серёжкой',
    year: '1665',
    imageNum: '109',
  },
  {
    author: 'Анри Руссо',
    picture: 'Спящая цыганка',
    year: '1897',
    imageNum: '110',
  },
  {
    author: 'Василий Поленов',
    picture: 'Переправа через реку',
    year: '1872',
    imageNum: '111',
  },
  {
    author: 'Эдвард Мунк',
    picture: 'Крик',
    year: '1893',
    imageNum: '112',
  },
  {
    author: 'Карл Брюллов',
    picture: 'Последний день Помпеи',
    year: '1833',
    imageNum: '113',
  },
  {
    author: 'Илья Репин',
    picture: 'Летний пейзаж',
    year: '1879',
    imageNum: '114',
  },
  {
    author: 'Ян Вермеер',
    picture: 'Молочница',
    year: '1660',
    imageNum: '115',
  },
  {
    author: 'Иван Айвазовский',
    picture: 'Девятый вал',
    year: '1850',
    imageNum: '116',
  },
  {
    author: 'Винсент ван Гог',
    picture: 'Подсолнухи',
    year: '1888',
    imageNum: '117',
  },
  {
    author: 'Валентин Серов',
    picture: 'Девочка с персиками',
    year: '1887',
    imageNum: '118',
  },
  {
    author: 'Караваджо',
    picture: 'Обращение Савла',
    year: '1601',
    imageNum: '119',
  },
  {
    author: 'Альбрехт Дюрер',
    picture: 'Праздник венков из роз',
    year: '1506',
    imageNum: '120',
  },
  {
    author: 'Эль Греко',
    picture: 'Изгнание торгующих из храма',
    year: '1600',
    imageNum: '121',
  },
  {
    author: 'Илья Репин',
    picture: 'Приготовление к экзамену',
    year: '1864',
    imageNum: '122',
  },
  {
    author: 'Исаак Левитан',
    picture: 'Март',
    year: '1895',
    imageNum: '123',
  },
  {
    author: 'Адольф Вильям Бугро',
    picture: 'Девушка и Амур',
    year: '1880',
    imageNum: '124',
  },
  {
    author: 'Леонардо да Винчи',
    picture: 'Мадонна Литта',
    year: '1491',
    imageNum: '125',
  },
  {
    author: 'Казимир Малевич',
    picture: 'Черный квадрат',
    year: '1915',
    imageNum: '126',
  },
  {
    author: 'Эль Греко',
    picture: 'Апостолы Петр и Павел',
    year: '1592',
    imageNum: '127',
  },
  {
    author: 'Виктор Васнецов',
    picture: 'Витязь на распутье',
    year: '1878',
    imageNum: '128',
  },
  {
    author: 'Константин Маковский',
    picture: 'Боярский свадебный пир',
    year: '1883',
    imageNum: '129',
  },
  {
    author: 'Эжен Делакруа',
    picture: 'Свобода, ведущая народ',
    year: '1830',
    imageNum: '130',
  },
  {
    author: 'Василий Поленов',
    picture: 'Бабушкин сад',
    year: '1878',
    imageNum: '131',
  },
  {
    author: 'Анри Матисс',
    picture: 'Семейный портрет',
    year: '1911',
    imageNum: '132',
  },
  {
    author: 'Константин Маковский',
    picture: 'Гадание',
    year: '1890',
    imageNum: '133',
  },
  {
    author: 'Пьер Огюст Ренуар',
    picture: 'Мост в Шату',
    year: '1875',
    imageNum: '134',
  },
  {
    author: 'Сандро Боттичелли',
    picture: 'Весна',
    year: '1482',
    imageNum: '135',
  },
  {
    author: 'Пьер Огюст Ренуар',
    picture: 'Зонтики',
    year: '1886',
    imageNum: '136',
  },
  {
    author: 'Гюстав Курбе',
    picture: 'Мастерская художника',
    year: '1855',
    imageNum: '137',
  },
  {
    author: 'Василий Поленов',
    picture: 'Деревня Окулова гора',
    year: '1860',
    imageNum: '138',
  },
  {
    author: 'Константин Маковский',
    picture: 'Перемещение ковра Мухаммеда из Мекки в Каир',
    year: '1875',
    imageNum: '139',
  },
  {
    author: 'Пьер Огюст Ренуар',
    picture: 'Бал в Мулен де ла Галетт',
    year: '1876',
    imageNum: '140',
  },
  {
    author: 'Иван Крамской',
    picture: 'Неизвестная',
    year: '1883',
    imageNum: '141',
  },
  {
    author: 'Веласкес',
    picture: 'Кузница вулкана',
    year: '1630',
    imageNum: '142',
  },
  {
    author: 'Илья Репин',
    picture: 'Запорожцы',
    year: '1891',
    imageNum: '143',
  },
  {
    author: 'Рафаэль',
    picture: 'Дама с единорогом',
    year: '1506',
    imageNum: '144',
  },
  {
    author: 'Александр Иванов',
    picture: 'Явление Христа народу',
    year: '1857',
    imageNum: '145',
  },
  {
    author: 'Эдуард Мане',
    picture: 'Женщина с кувшином',
    year: '1858',
    imageNum: '146',
  },
  {
    author: 'Тициан',
    picture: 'Конный портрет Карла V',
    year: '1548',
    imageNum: '147',
  },
  {
    author: 'Пьер Огюст Ренуар',
    picture: 'Завтрак гребцов',
    year: '1881',
    imageNum: '148',
  },
  {
    author: 'Карл Брюллов',
    picture: 'Итальянский полдень',
    year: '1827',
    imageNum: '149',
  },
  {
    author: 'Виктор Васнецов',
    picture: 'Царь Иван Васильевич Грозный',
    year: '1896',
    imageNum: '150',
  },
  {
    author: 'Питер Брейгель',
    picture: 'Охотники на снегу',
    year: '1565',
    imageNum: '151',
  },
  {
    author: 'Виктор Васнецов',
    picture: 'Ковер-самолёт',
    year: '1880',
    imageNum: '152',
  },
  {
    author: 'Марк Шагал',
    picture: 'Я и деревня',
    year: '1911',
    imageNum: '153',
  },
  {
    author: 'Леонардо да Винчи',
    picture: 'Мона Лиза',
    year: '1505',
    imageNum: '154',
  },
  {
    author: 'Франческо Баккьякка',
    picture: 'Мадонна с младенцем',
    year: '1520',
    imageNum: '155',
  },
  {
    author: 'Жак-Луи Давид',
    picture: 'Клятва Горациев',
    year: '1784',
    imageNum: '156',
  },
  {
    author: 'Альбрехт Дюрер',
    picture: 'Адам и Ева',
    year: '1507',
    imageNum: '157',
  },
  {
    author: 'Бартоломео Мурильо',
    picture: 'Явление и дар Богородицы',
    year: '1655',
    imageNum: '158',
  },
  {
    author: 'Василий Перов',
    picture: 'Птицелов',
    year: '1870',
    imageNum: '159',
  },
  {
    author: 'Караваджо',
    picture: 'Отдых на пути в Египет',
    year: '1596',
    imageNum: '160',
  },
  {
    author: 'Франциско Гоя',
    picture: 'Расстрел повстанцев',
    year: '1808',
    imageNum: '161',
  },
  {
    author: 'Рафаэль',
    picture: 'Триумф Галатеи',
    year: '1512',
    imageNum: '162',
  },
  {
    author: 'Михаил Врубель',
    picture: 'Демон сидящий',
    year: '1890',
    imageNum: '163',
  },
  {
    author: 'Винсент ван Гог',
    picture: 'Ирисы',
    year: '1889',
    imageNum: '164',
  },
  {
    author: 'Поль Деларош',
    picture: 'Казнь Джейн Грей',
    year: '1833',
    imageNum: '165',
  },
  {
    author: 'Джон Констебл',
    picture: 'Вид на собор в Солсбери из епископского сада',
    year: '1823',
    imageNum: '166',
  },
  {
    author: 'Винсент ван Гог',
    picture: 'Звёздная ночь',
    year: '1889',
    imageNum: '167',
  },
  {
    author: 'Франсуа Буше',
    picture: 'Четыре сезона - Весна',
    year: '1755',
    imageNum: '168',
  },
  {
    author: 'Рафаэль',
    picture: 'Мадонна с розой',
    year: '1518',
    imageNum: '169',
  },
  {
    author: 'Василий Тропинин',
    picture: 'Кружевница',
    year: '1823',
    imageNum: '170',
  },
  {
    author: 'Рембрандт',
    picture: 'Пир Вальтасара',
    year: '1635',
    imageNum: '171',
  },
  {
    author: 'Василий Суриков',
    picture: 'Переход Суворова через Альпы',
    year: '1899',
    imageNum: '172',
  },
  {
    author: 'Исаак Левитан',
    picture: 'Золотая осень',
    year: '1895',
    imageNum: '173',
  },
  {
    author: 'Архип Куинджи',
    picture: 'На острове Валааме',
    year: '1873',
    imageNum: '174',
  },
  {
    author: 'Веласкес',
    picture: 'Сдача Бреды',
    year: '1635',
    imageNum: '175',
  },
  {
    author: 'Илья Репин',
    picture: 'Не ждали',
    year: '1888',
    imageNum: '176',
  },
  {
    author: 'Франсуа Буше',
    picture: 'Купание Дианы',
    year: '1742',
    imageNum: '177',
  },
  {
    author: 'Марианна Верёвкина',
    picture: 'Муравейник',
    year: '1916',
    imageNum: '178',
  },
  {
    author: 'Пьер Огюст Ренуар',
    picture: 'Портрет Жанны Самари',
    year: '1877',
    imageNum: '179',
  },
  {
    author: 'Илья Репин',
    picture: 'Садко',
    year: '1876',
    imageNum: '180',
  },
  {
    author: 'Архип Куинджи',
    picture: 'Лунная ночь на Днепре',
    year: '1880',
    imageNum: '181',
  },
  {
    author: 'Веласкес',
    picture: 'Поклонение волхвов',
    year: '1619',
    imageNum: '182',
  },
  {
    author: 'Николай Богданов-Бельский',
    picture: 'У дверей школы',
    year: '1897',
    imageNum: '183',
  },
  {
    author: 'Иероним Босх',
    picture: 'Сад земных наслаждений',
    year: '1510',
    imageNum: '184',
  },
  {
    author: 'Корреджо',
    picture: 'Даная',
    year: '1530',
    imageNum: '185',
  },
  {
    author: 'Питер Пауль Рубенс',
    picture: 'Похищение дочерей Левкиппа',
    year: '1618',
    imageNum: '186',
  },
  {
    author: 'Жан Энгр',
    picture: 'Большая одалиска',
    year: '1814',
    imageNum: '187',
  },
  {
    author: 'Рафаэль',
    picture: 'Сикстинская Мадонна',
    year: '1520',
    imageNum: '188',
  },
  {
    author: 'Рембрандт',
    picture: 'Похищение Европы',
    year: '1632',
    imageNum: '189',
  },
  {
    author: 'Питер Пауль Рубенс',
    picture: 'Похищение Орфии Бореем',
    year: '1615',
    imageNum: '190',
  },
  {
    author: 'Архип Куинджи',
    picture: 'Украинская ночь',
    year: '1876',
    imageNum: '191',
  },
  {
    author: 'Эдгар Дега',
    picture: 'Танцовщицы у станка',
    year: '1877',
    imageNum: '192',
  },
  {
    author: 'Алексей Венецианов',
    picture: 'На жатве. Лето',
    year: '1827',
    imageNum: '193',
  },
  {
    author: 'Пьер Огюст Ренуар',
    picture: 'Две сестры',
    year: '1881',
    imageNum: '194',
  },
  {
    author: 'Рембрандт',
    picture: 'Ночной дозор',
    year: '1642',
    imageNum: '195',
  },
  {
    author: 'Эдуар Мане',
    picture: 'Бар в «Фоли-Бержер»',
    year: '1882',
    imageNum: '196',
  },
  {
    author: 'Никола Пуссен',
    picture: 'Пейзаж с Полифемом',
    year: '1649',
    imageNum: '197',
  },
  {
    author: 'Питер Брейгель',
    picture: 'Притча о слепых',
    year: '1568',
    imageNum: '198',
  },
  {
    author: 'Виктор Васнецов',
    picture: 'Иван-царевич на Сером Волке',
    year: '1888',
    imageNum: '199',
  },
  {
    author: 'Сандро Боттичелли',
    picture: 'Рождение Венеры',
    year: '1486',
    imageNum: '200',
  },
  {
    author: 'Леонардо да Винчи',
    picture: 'Мадонна в скалах',
    year: '1486',
    imageNum: '201',
  },
  {
    author: 'Аксели Галлен-Каллела',
    picture: 'Любовники',
    year: '1916',
    imageNum: '202',
  },
  {
    author: 'Винсент Ван Гог',
    picture: 'Автопортрет с перевязанным ухом',
    year: '1889',
    imageNum: '203',
  },
  {
    author: 'Клод Моне',
    picture: 'Впечатление. Восходящее солнце',
    year: '1882',
    imageNum: '204',
  },
  {
    author: 'Рембрандт',
    picture: 'Возвращение блудного сына',
    year: '1662',
    imageNum: '205',
  },
  {
    author: 'Караваджо',
    picture: 'Больной вакх',
    year: '1593',
    imageNum: '206',
  },
  {
    author: 'Иван Айвазовский',
    picture: 'Лунная дорожка',
    year: '1886',
    imageNum: '207',
  },
  {
    author: 'Винсент Ван Гог',
    picture: 'Пшеничное поле с кипарисами',
    year: '1889',
    imageNum: '208',
  },
  {
    author: 'Аксели Галлен-Каллела',
    picture: 'Мальчик и ворона',
    year: '1884',
    imageNum: '209',
  },
  {
    author: 'Ян Вермеер',
    picture: 'Астроном',
    year: '1668',
    imageNum: '210',
  },
  {
    author: 'Питер Пауль Рубенс',
    picture: 'Союз Земли и Воды',
    year: '1618',
    imageNum: '211',
  },
  {
    author: 'Клод Моне',
    picture: 'Стог сена в Живерни',
    year: '1886',
    imageNum: '212',
  },
  {
    author: 'Жан Фрагонар',
    picture: 'Задвижка',
    year: '1777',
    imageNum: '213',
  },
  {
    author: 'Марианна Верёвкина',
    picture: 'Осень, школа',
    year: '1907',
    imageNum: '214',
  },
  {
    author: 'Винсент Ван Гог',
    picture: 'Ночное кафе в Арле',
    year: '1888',
    imageNum: '215',
  },
  {
    author: 'Клод Моне',
    picture: 'Пруд с кувшинками',
    year: '1899',
    imageNum: '216',
  },
  {
    author: 'Иван Айвазовский',
    picture: 'Буря',
    year: '1868',
    imageNum: '217',
  },
  {
    author: 'Ян Вермеер',
    picture: 'Кружевница',
    year: '1671',
    imageNum: '218',
  },
  {
    author: 'Карл Брюллов',
    picture: 'Автопортрет',
    year: '1848',
    imageNum: '219',
  },
  {
    author: 'Питер Брейгель',
    picture: 'Вавилонская башня',
    year: '1563',
    imageNum: '220',
  },
  {
    author: 'Поль Гоген',
    picture: 'Кафе в Арле',
    year: '1888',
    imageNum: '221',
  },
  {
    author: 'Иван Шишкин',
    picture: 'Сосновый бор',
    year: '1895',
    imageNum: '222',
  },
  {
    author: 'Клод Моне',
    picture: 'Завтрак на траве',
    year: '1865',
    imageNum: '223',
  },
  {
    author: 'Рафаэль',
    picture: 'Святой Георгий и дракон',
    year: '1506',
    imageNum: '224',
  },
  {
    author: 'Пабло Пикассо',
    picture: 'Любительница абсента',
    year: '1901',
    imageNum: '225',
  },
  {
    author: 'Эдгар Дега',
    picture: 'Перед репетицией',
    year: '1880',
    imageNum: '226',
  },
  {
    author: 'Николай Рерих',
    picture: 'Помни!',
    year: '1924',
    imageNum: '227',
  },
  {
    author: 'Илья Репин',
    picture: 'Стрекоза',
    year: '1884',
    imageNum: '228',
  },
  {
    author: 'Клод Моне',
    picture: 'Мост Ватерлоо, туман',
    year: '1903',
    imageNum: '229',
  },
  {
    author: 'Исаак Левитан',
    picture: 'Весна – большая вода',
    year: '1897',
    imageNum: '230',
  },
  {
    author: 'Аксели Галлен-Каллела',
    picture: 'Первый урок',
    year: '1889',
    imageNum: '231',
  },
  {
    author: 'Иван Айвазовский',
    picture: 'Буря на море',
    year: '1873',
    imageNum: '232',
  },
  {
    author: 'Эдгар Дега',
    picture: 'Балетный класс',
    year: '1874',
    imageNum: '233',
  },
  {
    author: 'Николай Рерих',
    picture: 'Горная обитель',
    year: '1933',
    imageNum: '234',
  },
  {
    author: 'Леонардо да Винчи',
    picture: 'Святая Анна с Мадонной',
    year: '1510',
    imageNum: '235',
  },
  {
    author: 'Эль Греко',
    picture: 'Мальчик, зажигающий свечу',
    year: '1572',
    imageNum: '236',
  },
  {
    author: 'Пабло Пикассо',
    picture: 'Дружба',
    year: '1908',
    imageNum: '237',
  },
  {
    author: 'Аксели Галлен-Каллела',
    picture: 'Девушка на ветру',
    year: '1893',
    imageNum: '238',
  },
  {
    author: 'Иван Айвазовский',
    picture: 'Волна',
    year: '1889',
    imageNum: '239',
  },
  {
    author: 'Эжен Делакруа',
    picture: 'Автопортрет',
    year: '1837',
    imageNum: '240',
  },
];

export default images;
